spring:
  profiles:
    include:
      - security

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springsecurityjwt;MODE=MYSQL
    username: sa

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true