security:
  cors:
    allow-credentials: false
    allowed-headers: '*'
    allowed-methods: GET, POST, PUT, DELETE
    allowed-origins: http://localhost:8080
    max-age: 1800

  jwt:
    secret-key: secret
    valid-seconds: 60